### ISSUE TITLE
update.sh that updates minishell_tester

### ISSUE THREAD

**Issue by francisrafal** [francisrafal/minishell_tester#6]
Something like:
```
minishell_tester -u
```
or 
```
minishell_tester --update
```

**Comment by hu8813** [comment]
as i am new in python, i asked chatgpt :) it wrote a python script which checks for latest commit, compares with local rep and updates if there is a new one, tested.

**Comment by francisrafal** [comment]
awesome, thanks! Will merge after testing tomorrow!
